name: pypely
dependencies:
  - python=3.9
  - pip:
    - toml
    - pre-commit
    - twine
    - seaborn
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-html
    - "-e ."
    - torch
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - tensorboard
    - mlflow
    - tqdm
    - pillow
    - pydocstyle
    - darglint
    - black
    - isort
    - pycln
    - black
    - mypy
    - lxml