name: pypely
dependencies:
  - python=3.7
  - pip:
    - twine
    - seaborn
    - pytest
    - "."
    - torch
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - tensorboard
    - mlflow
    - tqdm
    - pillow