name: pypely
dependencies:
  - python=3.9
  - pip:
    - pre-commit
    - twine
    - seaborn
    - pytest
    - pytest-mock
    - pytest-html
    - "-e ."
    - torch
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - tensorboard
    - mlflow
    - tqdm
    - pillow