[tool.semantic_release]
version_variable = [
    "setup.py:__version__"
]
branch = "main"
build_command = "python setup.py sdist bdist_wheel"
remove_dist = false
upload_to_pypi = true
upload_to_release = true