name: Assure Code Quality

on:
  pull_request:
    branches: [ main ]

jobs:
  assure-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Clean imports
        run: |
          pycln --check .
      - name: Sort imports
        run: |
          isort --check --profile black . --line-length=119
      - name: Format code
        run: |
          black . --check --line-length=119
      - name: Check docstring format
        run: |
          pydocstyle --add-ignore=D107 --match-dir="(?!tests)(.*)"
      - name: Check docstring correctness
        run: |
          darglint .
      - name: Check types
        run: |
          mypy ./src --ignore-missing-imports --install-types --non-interactive --html-report ./mypy
      - name: Show mypy report
        id: mypy_report
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: './mypy/index.html'
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format('[Click here to check out the mypy report]({0})', steps.mypy_report.outputs.url) }}
      - name: Run unit tests
        run: |
          export PYTHONPATH=/home/runner/work/pypely/pypely/src:/home/runner/work/pypely/pypely/examples
          pytest --cov-report xml:package_cov.xml --cov=src tests/
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./package_cov.xml
