environment: release

on:
  merge:
    branches: [release]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@1.2.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.PR.outputs.pr_body }}
          draft: false
          prerelease: false
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Upload to pypi
        id: pypi_upload
        run: |
          python setup.py sdist bdist_wheel
          twine upload --non-interactive --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
      - name: Tag version
        run: |
          git tag -a v$(python setup.py --version) -m 'tag release'