name: Python application

on:
  pull_request:
    branches: [ main, release ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'PACKAGE_VERSION'
        value: '0.0.1'
        repository: hmanzur/actions-set-secret
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
